In [1]:
import scipy.stats as spt
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

In [ ]:
import rpy2.robjects as robjs
from rpy2.robjects import r
%load_ext rpy2.ipython
# 변수 이동
%Rpush data1

In [ ]:
print(r('aov_mdl <- aov(data1$miles ~ as.factor(data1$pad),data=data1)'))

In [ ]:
robjs.packages.importr('agricolae')
print(r('duncan.test(aov_mdl, "as.factor(data1$pad)", alpha = 0.05, console = TRUE)'))

In [11]:
# 카이제곱 검정 (적합도)

print(spt.chisquare([16, 18, 16, 14, 12, 12]))

print(spt.chisquare([16, 18, 16, 14, 12, 12], f_exp=[16, 16, 16, 16, 16, 8]))

print(spt.chisquare([16, 18, 16, 14, 12, 12], ddof=[0,1,2]))

obs=np.array([31,26,22,18,13,10])
print(spt.chisquare(obs))

Power_divergenceResult(statistic=2.0, pvalue=0.8491450360846096)
Power_divergenceResult(statistic=3.5, pvalue=0.6233876277495822)
Power_divergenceResult(statistic=2.0, pvalue=array([0.84914504, 0.73575888, 0.5724067 ]))
Power_divergenceResult(statistic=15.7, pvalue=0.007754884452437287)


In [2]:
# 카이제곱 검정 (적합도)

print(spt.chisquare([16, 18, 16, 14, 12, 12]))

print(spt.chisquare([16, 18, 16, 14, 12, 12], f_exp=[16, 16, 16, 16, 16, 8]))

print(spt.chisquare([16, 18, 16, 14, 12, 12], ddof=[0,1,2]))

obs=np.array([31,26,22,18,13,10])
print(spt.chisquare(obs))

Power_divergenceResult(statistic=2.0, pvalue=0.8491450360846096)
Power_divergenceResult(statistic=3.5, pvalue=0.6233876277495822)
Power_divergenceResult(statistic=2.0, pvalue=array([0.84914504, 0.73575888, 0.5724067 ]))
Power_divergenceResult(statistic=15.7, pvalue=0.007754884452437287)


In [4]:
# 카이제곱 검정 (교차분석)
homd=pd.read_csv('hom_ind.csv',dtype={'QUALITY' : 'object'})
homd.head()

COUNTS LINE QUALITY
0      20    A       1
1      16    A       2
2      24    A       3
3      28    A       4
4      12    A       5

In [5]:
print(spt.chi2_contingency([homd.COUNTS[homd.QUALITY=='1'],homd.COUNTS[homd.QUALITY=='2'],
                           homd.COUNTS[homd.QUALITY=='3'],homd.COUNTS[homd.QUALITY=='4'],homd.COUNTS[homd.QUALITY=='5']]))

(38.91388658559004, 0.00010872733726640437, 12, array([[15.5 , 15.5 , 15.5 , 15.5 ],
       [21.  , 21.  , 21.  , 21.  ],
       [20.5 , 20.5 , 20.5 , 20.5 ],
       [21.75, 21.75, 21.75, 21.75],
       [21.25, 21.25, 21.25, 21.25]]))


In [6]:
ss=np.array([[homd.COUNTS[0:5]],[homd.COUNTS[5:10]],[homd.COUNTS[10:15]],[homd.COUNTS[15:20]]])
print(ss)

[[[20 16 24 28 12]]

 [[13 17 30 15 25]]

 [[20 20 15 15 30]]

 [[ 9 31 13 29 18]]]


In [7]:
t_chi2=0
for i in range(4):
    for j in range(5):
        O = ss[i][0][j]
        E = (ss[i][0][0]+ss[i][0][1]+ss[i][0][2]+ss[i][0][3]+ss[i][0][4])*(ss[0][0][j]+ss[1][0][j]+ss[2][0][j]+ss[3][0][j]) / 400
        t_chi2 += (O-E)**2/E
print(t_chi2)

38.913886585590035


In [8]:
p_val = 1 - spt.chi2.cdf(t_chi2, 12)
print(p_val)

0.00010872733726641215
